#!/bin/bash
LiveNodes="$(echo `sudo eb health --view status | grep -a "total" -A 1 | awk -F ' ' '{print $1}' | sed -n '/total/{n;p;}'`)"
echo Number of Live Nodes - $LiveNodes
count=1 
echo "The command we are going to run is - $*"
echo "Press Any Key if you are sure to continue..."
read
while [ $count -le $LiveNodes ] 
do
echo "Output from No. $count Instance"
sudo eb ssh -n $count --command "$*" | grep -v "INFO"
echo ""
echo ""
(( count++ ))
done
