#!/bin/bash
LiveNodes="$(echo `sudo eb health --view status | grep -a "total" -A 1 | awk -F ' ' '{print $1}' | sed -n '/total/{n;p;}'`)"
echo Number of Live Nodes - $LiveNodes
count=1 
echo -e "The command we are going to run is - \e[31m $* \e[0m"
echo "Press Any Key if you are sure to continue..."
read
while [ $count -le $LiveNodes ] 
do
echo -e "Output from No. \e[31m $count \e[0m Instance"
echo -e "\e[31m"
sudo eb ssh -n $count --command "$*" | grep -v "INFO"
echo -e "\e[0m"
echo ""
(( count++ ))
done
